apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
metadata:
  name: mediawiki-postgresql-binding
  namespace: default
spec:
  instanceRef:
    name: postgresql
  secretName: mediawiki-postgresql-binding
  alphaPodPresetTemplate:
    name: bind-postgresql-mediawiki
    selector:
      matchLabels:
        app: mediawiki123
