apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: postgresql
  namespace: default
spec:
  clusterServiceClassExternalName: dh-rhscl-postgresql-apb
  clusterServicePlanExternalName: prod
  parameters:
    postgresql_database: "admin"
    postgresql_password: "admin"
    postgresql_user: "admin"
    postgresql_version: "9.5"
