engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
    checks:
      GoLint/Comments/DocComments:
        enabled: false
      GoLint/Naming/Initialisms:
        enabled: false
      TODO:
        enabled: false
      HACK:
        enabled: false
  govet:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
- test/
