language: go
go:
  - "1.8.x"
dist: trusty
sudo: required
group: edge
env:
  - CHANGE_MINIKUBE_NONE_USER=true

jobs:
  include:
    - stage: "OpenShift and Kubernetes CI"
      before_install:
        # Copied from https://github.com/facebook/react/pull/2000
        - |
            if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
              TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
            fi
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/' || {
              echo "Only docs were updated, stopping build process."
              exit 0
            }
        - ./scripts/travis.sh before_install
      install:
        - ./scripts/travis.sh install
      before_script:
        - ./scripts/travis.sh before_script
        - ./scripts/travis.sh format
        - ./scripts/travis.sh vet
        - ./scripts/travis.sh lint
        - ./scripts/travis.sh build
        - ./scripts/travis.sh test
        - ./scripts/travis.sh setup-cluster
        - ./scripts/travis.sh setup-broker
      script:
        - ./scripts/travis.sh ci
        - ./scripts/broker-ci/gather-logs.sh
    -
      before_install:
        # Copied from https://github.com/facebook/react/pull/2000
        - |
            if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
              TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
            fi
            git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/' || {
              echo "Only docs were updated, stopping build process."
              exit 0
            }
      before_script:
        - ./scripts/travis.sh setup-minikube
        - ./scripts/travis.sh k8s-catalog
        - ./scripts/travis.sh k8s-broker
      script:
        - ./scripts/travis.sh k8s-ci
        - ./scripts/broker-ci/gather-logs.sh
