language: go
go:
  - "1.8.x"
dist: trusty
sudo: required
group: edge

before_install:
  - ./scripts/travis.sh before_install
install:
  - ./scripts/travis.sh install
before_script:
  - ./scripts/travis.sh before_script
script:
  - ./scripts/travis.sh format
  - ./scripts/travis.sh vet
  - ./scripts/travis.sh lint
  - ./scripts/travis.sh build
  - ./scripts/travis.sh test
  - ./scripts/travis.sh ci
  - docker ps -a | grep mediawiki
  - docker logs $(docker ps -a | grep mediawiki123_mediawiki123 | awk '{ print $1 }')
  - ./scripts/broker-ci/gather-logs.sh
