language: go
go:
  - "1.8.x"
dist: trusty
sudo: required
group: edge

before_install:
  - ./scripts/travis.sh before_install
install:
  - ./scripts/travis.sh install
before_script:
  - ./scripts/travis.sh before_script
script:
  - ./scripts/travis.sh format
  - ./scripts/travis.sh vet
  - ./scripts/travis.sh lint
  - ./scripts/travis.sh build
  - ./scripts/travis.sh test
  - ./scripts/travis.sh setup-cluster
  - ./scripts/travis.sh setup-broker
  - ./scripts/travis.sh ci
  - ./scripts/broker-ci/gather-logs.sh
  - 'oc get pods --all-namespaces'
