language: go
go:
  - "1.7.x"
dist: trusty
sudo: required
group: edge

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-apt autoconf pkg-config e2fslibs-dev libblkid-dev zlib1g-dev liblzo2-dev asciidoc
install:
  - sudo pip install ansible==2.3.1
  - ./scripts/travis.sh install
before_script:
  - sudo ufw disable
  - tmp=`mktemp`
  - echo '{"insecure-registries":["172.30.0.0/16"]}' > ${tmp}
  - sudo mv ${tmp} /etc/docker/daemon.json
  - sudo mount --make-shared /
  - sudo service docker restart
script:
  - ./scripts/travis.sh format
  - ./scripts/travis.sh vet
  - ./scripts/travis.sh lint
  - ./scripts/travis.sh build
  - ./scripts/travis.sh test
  - ./scripts/travis.sh ci
  - oc login --insecure-skip-tls-verify 172.17.0.1:8443 -u admin -p admin
  - oc project default
  - make build-image
  - make deploy
  - sleep 15
  - oc create -f scripts/broker-ci/broker-resource.yaml
  - oc get serviceclasses --all-namespaces
  - oc create -f ./scripts/broker-ci/mediawiki123.yaml
  - oc create -f ./scripts/broker-ci/postgresql.yaml
  - ./scripts/broker-ci/wait-for-pods.sh
  - sleep 30
  - oc create -f ./scripts/broker-ci/bind-mediawiki-postgresql.yaml
  - sleep 5
  - oc get secrets --all-namespaces | grep mediawiki-postgresql-binding
  - oc get secret mediawiki-postgresql-binding -o yaml -n default
  - oc get podpresets -n default
  - oc get pods $(oc get pods -n default | grep mediawiki | awk $'{ print $1 }') -o yaml -n default
  - oc delete pods $(oc get pods -n default | grep mediawiki | awk $'{ print $1 }') -n default
  - sleep 20
  - oc get pods $(oc get pods -n default | grep mediawiki | awk $'{ print $1 }') -o yaml -n default
  - oc get pods --all-namespaces
  - curl $(oc get route -n default | grep mediawiki | cut -f 4 -d ' ')/index.php/Main_Page
  - oc logs $(oc get pods -o name -l service=asb --all-namespaces | cut -f 2 -d '/')
