language: go
go:
  - "1.8.x"
dist: trusty
sudo: required
group: edge

before_install:
  - ./scripts/travis.sh before_install
install:
  - ./scripts/travis.sh install
before_script:
  - ./scripts/travis.sh before_script
script:
  - ./scripts/travis.sh format
  - ./scripts/travis.sh vet
  - ./scripts/travis.sh lint
  - ./scripts/travis.sh build
  - ./scripts/travis.sh test
  - ./scripts/travis.sh ci
  - kubectl get pods
  - kubectl get secrets
  - oc get routes
  - curl -H "authorization: bearer $(oc whoami -t)"  https://asb-1338-ansible-service-broker.172.17.0.1.nip.io/ansible-service-broker/v2/catalog --insecure
