language: go
go:
  - "1.7.x"
dist: trusty
sudo: required
group: edge

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-apt autoconf pkg-config e2fslibs-dev libblkid-dev zlib1g-dev liblzo2-dev asciidoc
install:
  - sudo pip install ansible==2.3.1
  - ./scripts/travis.sh install
before_script:
  - sudo ufw disable
  - tmp=`mktemp`
  - echo '{"insecure-registries":["172.30.0.0/16"]}' > ${tmp}
  - sudo mv ${tmp} /etc/docker/daemon.json
  - sudo mount --make-shared /
  - sudo service docker restart
script:
  - ./scripts/travis.sh format
  - ./scripts/travis.sh vet
  - ./scripts/travis.sh lint
  - ./scripts/travis.sh build
  - ./scripts/travis.sh test
  - ./scripts/travis.sh ci
  - ifconfig
  - ifconfig docker0 | grep inet | awk '{print $2}' | head -1 | cut -f 2 -d ':'
  - oc login -u system:admin
  - oc project default
  - make build-image
  - make deploy
  - sleep 15
  - oc logs $(oc get pods -o name -l service=asb --all-namespaces | cut -f 2 -d '/')
  - oc get serviceclasses
  - oc create -f ./scripts/broker-ci/mediawiki123.yaml
  - oc create -f ./scripts/broker-ci/postgresql.yaml
  - oc get instances
  - sleep 20
  - oc create -f ./scripts/broker-ci/bind-mediawiki-postgresql.yaml
  - sleep 10
  - oc get secrets
  - oc get secret mediawiki-postgresql-binding -o yaml
  - oc get podpresets
  - oc get pods
  - curl $(oc get route | grep mediawiki | cut -f 4 -d ' ')/index.php/Main_Page
