# The following variables need to be set at the bottom of the template
#   DOCKERHUB_ORG     - Dockerhub organization name
#   DOCKERHUB_USER    - Dockerhub username
#   DOCKERHUB_PASS    - Dockerhub password
#
# Create the broker with:
#   oc create -f ansible-service-broker-all.yaml
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: ansible-service-broker

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asb
  namespace: ansible-service-broker

---
apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: asb
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: asb
  namespace: ansible-service-broker

---
apiVersion: v1
kind: Service
labels:
   app: ansible-service-broker
   service: asb
metadata:
   name: asb
   namespace: ansible-service-broker
spec:
  ports:
    - name: port-1338
      port: 1338
  selector:
    app: ansible-service-broker
    service: asb

---
apiVersion: v1
kind: Service
metadata:
   name: etcd
   namespace: ansible-service-broker
spec:
  ports:
    - name: etcd-advertise
      port: 2379
  selector:
    app: ansible-service-broker
    service: etcd

---
apiVersion: v1
kind: Route
metadata:
  name: asb-1338
  namespace: ansible-service-broker
  labels:
    app: ansible-service-broker
    service: asb
spec:
  to:
    kind: Service
    name: asb
  port:
    targetPort: port-1338


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd
  namespace: ansible-service-broker
  labels:
    app: ansible-service-broker
    service: etcd
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ansible-service-broker
        service: etcd
    spec:
      restartPolicy: Always
      containers:
        - image: ansibleapp/ansible-service-broker-etcd:latest
          name: main
          imagePullPolicy: IfNotPresent
          workingDir: /etcd
          args:
            - ./etcd
            - --data-dir=/data
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://0.0.0.0:2379
          ports:
          - containerPort: 2379
            protocol: TCP
          env:
          - name: ETCDCTL_API
            value: "3"
          volumeMounts:
            - mountPath: /data
              name: etcd
      volumes:
        - name: etcd
          persistentVolumeClaim:
            claimName: etcd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asb
  namespace: ansible-service-broker
  labels:
    app: ansible-service-broker
    service: asb
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ansible-service-broker
        service: asb
    spec:
      restartPolicy: Always
      serviceAccount: asb
      containers:
        - image: "ansibleplaybookbundle/ansible-service-broker:latest"
          name: asb
          # Setting to IfNotPresent to allow testing with local images
          # Alternative is to set to Always to ensure we are always running latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1338
              protocol: TCP
          env:
            - name: DOCKERHUB_PASS
              value: "{{dockerhub_pass}}"
            - name: DOCKERHUB_USER
              value: "{{dockerhub_user}}"
            - name: DOCKERHUB_ORG
              value: "{{dockerhub_org}}"
