# Travis CI
provision: mediawiki123
verify: rthallisey/service-broker-ci/wait-for-resource.sh create pod mediawiki

provision: postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh create pod postgresql

bind: postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh create bindings.v1alpha1.servicecatalog.k8s.io binding

verify: rthallisey/service-broker-ci/verify-bind.sh mediawiki123

unbind: postgresql | mediawiki123
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete bindings.v1alpha1.servicecatalog.k8s.io binding

deprovision: mediawiki123
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete instance mediawiki

deprovision: postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete instance postgresql
