# Travis CI
provision: ansibleplaybookbundle/mediawiki123-apb
provision: ansibleplaybookbundle/rhscl-postgresql-apb

bind: ansibleplaybookbundle/rhscl-postgresql-apb
verify: rthallisey/service-broker-ci/verify-mediawiki-postgresql.sh
unbind: rhscl-postgresql-apb | mediawiki123-apb

deprovision: ansibleplaybookbundle/mediawiki123-apb
deprovision: ansibleplaybookbundle/rhscl-postgresql-apb
