provision: rthallisey/service-broker-ci/mediawiki123
verify: rthallisey/service-broker-ci/wait-for-resource.sh create pod mediawiki

provision: rthallisey/service-broker-ci/postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh create pod postgresql

bind: rthallisey/service-broker-ci/postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh create bindings.v1alpha1.servicecatalog.k8s.io binding
verify: rthallisey/service-broker-ci/wait-for-resource.sh create podpreset binding

# The verify field is run as a shell command
verify: rthallisey/service-broker-ci/verify-bind.sh mediawiki123

# The BindApp is the application that will be binded to the BindTarget.
# Format:
#      <BindApp> | <BindTarget>
#
unbind: postgresql | mediawiki123
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete bindings.v1alpha1.servicecatalog.k8s.io binding

deprovision: rthallisey/service-broker-ci/mediawiki123
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete pod mediawiki

deprovision: rthallisey/service-broker-ci/postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete pod postgresql
