# Travis CI
provision: ansibleplaybookbundle/mediawiki-apb
provision: ansibleplaybookbundle/postgresql-apb

bind: ansibleplaybookbundle/postgresql-apb
verify: shawn-verify-mediawiki-postgresql.sh
unbind: postgresql-apb | mediawiki-apb

deprovision: ansibleplaybookbundle/mediawiki-apb
deprovision: ansibleplaybookbundle/postgresql-apb
