---
apiVersion: "automationbroker.io/v1alpha1"
kind: "AutomationBroker"
metadata:
  name: automation-broker-operator
  namespace: automation-broker
spec:
  brokerImagePullPolicy: IfNotPresent
  createBrokerNamespace: false
  waitForBroker: false
################################################################################
# Some other example overrides, in general most defaults will work.
################################################################################
#  brokerName: automation-broker
#  brokerImage: "ansibleplaybookbundle/origin-ansible-service-broker"
#  brokerClusterRole: admin
#  brokerNodeSelector: ""
#  brokerConfig:
#    dao:
#      type: crd
#    log:
#      logfile: /var/log/ansible-service-broker/asb.log
#      stdout: true
#      level: debug
#      color: true
#    openshift:
#      imagePullPolicy: Always
#      sandboxRole: edit
#      namespace: automation-broker
#      keepNamespace: false
#      keepNamespaceOnError: true
#    broker:
#      devBroker: false
#      bootstrapOnStartup: true
#      refreshInterval: 60s
#      launchApbOnBind: false
#      outputRequest: false
#      recovery: true
#      sslCertKey: /etc/tls/private/tls.key
#      sslCert: /etc/tls/private/tls.crt
#      autoEscalate: true
#      auth:
#        - type: basic
#          enabled: false
#    registry:
#      - type: dockerhub
#        name: hc
#        url: https://registry.hub.docker.com
#        org: homecluster
#        tag: latest
#        whiteList: [ ".*" ]
