---

- name: Prepare operator resources
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
  tasks:
  - name: Create Custom Resource Definition
    k8s:
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/osb_v1alpha1_automationbroker_crd.yaml'])) }}"

  - name: Create bundle crd
    k8s:
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/bundle.crd.yaml'])) }}"

  - name: Create bundle bindings crd
    k8s:
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/bundlebindings.crd.yaml'])) }}"

  - name: Create bundle instance crd
    k8s:
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/bundleinstances.crd.yaml'])) }}"

  - name: Ensure specified namespace is present
    k8s:
      api_version: v1
      kind: Namespace
      name: '{{ namespace }}'

  - name: Create RBAC resources
    k8s:
      definition: "{{ lookup('template', '/'.join([deploy_dir, item])) }}"
      namespace: '{{ namespace }}'
    with_items:
      - role.yaml
      - role_binding.yaml
      - service_account.yaml

  - name: Create ServiceCatalog ApiServer and ControllerManager
    k8s:
      definition:
        apiVersion: operator.openshift.io/v1
        kind: '{{ item }}'
        metadata:
          name: cluster
        spec:
          logLevel: Normal
          managementState: Managed
    with_items:
    - ServiceCatalogAPIServer
    - ServiceCatalogControllerManager

  - name: Wait 5m for Service Catalog Controller Manager to be complete
    k8s_facts:
      api_version: "operator.openshift.io/v1"
      kind: "ServiceCatalogControllerManager"
      namespace: ""
      name: "cluster"
    register: svccat_cm
    until:
    - "[ \"True\" ] in (svccat_cm | json_query('resources[].status.conditions[?type==`Available`].status'))"
    delay: 10
    retries: 30


    
