---
registry:
  name: dockerhub
  url: http://localhost:1337
  user: DOCKERHUB_USER
  pass: DOCKERHUB_PASS
  org: DOCKERHUB_ORG
dao:
  etcd_host: localhost
  etcd_port: 2379
log:
  logfile: /var/log/ansible-service-broker/asb.log
  stdout: true
  level: debug
  color: true
openshift:
  target: localhost:8443
  user: OPENSHIFT_USER
  pass: OPENSHIFT_PASS
  image_pull_policy: IfNotPresent
broker:
  dev_broker: true
  launch_apb_on_bind: false
  recovery: true
  output_request: true
