---

- name: automation-broker-operator
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  roles:
  - role: automation-broker
  vars:
    state: present
    broker_name: "{{ meta.name }}"
    broker_namespace: "{{ meta.namespace }}"
