apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: mediawiki-postgresql-binding
  namespace: default
spec:
  instanceRef:
    name: postgresql
  secretName: mediawiki-postgresql-binding
