---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: broker-redirector
  namespace: {{ broker_namespace }}
  labels:
    app: {{ broker_name }}
    service: broker
spec:
  to:
    kind: Service
    name: broker
  port:
    targetPort: port-1337
